/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicegameapp;

import java.util.ArrayList;
import java.util.Vector;

/**
 *
 * @author zeyuzhang
 */
public class RankBoardPage extends javax.swing.JFrame {

    /**
     * Creates new form RankBoardPage
     */
    private ArrayList<Vector<RankRecord>> rankBoard;
    
    public RankBoardPage(ArrayList<Vector<RankRecord>> newRankBoard) {
        initComponents();
        rankBoard = newRankBoard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        textArea.setViewportView(jTextArea1);
        jTextArea1.setEditable(false);
        jTextArea1.setText(s);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_backButtonActionPerformed
    
    public String printRankBoard(){
    	String result = "";
    	
    	if(rankBoard.size() == 0){
            result += "\t\tNo Record!!\n";
        }
       
        else{
            result += "===========================================================\n";
            result += "\n\t\tRanking Board\n\n";
            result += "===========================================================\n";
            
            for(int i = 0; i < rankBoard.size(); i++){
                result += "\t\tRound %d\n" + (i + 1);
                
                Vector<RankRecord> record = rankBoard.get(i);
                
                for(int j = 0; j < record.size(); j++){
                	if( record.get(j).isTie() ){
                		result += "\t\tTied!!! NO WINNER :(\n";
                	}
                	else{
                		result += "\t\tWinner:\t%s\n" + record.get(j).getWinnerName();
                		result += "\t\tScore:\t%d\n" + record.get(j).getWinnerScore();
                	}
                }
                
                result += "-----------------------------------------------------------\n";
            }
        }
        return result;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane textArea;
    private String s = "asfdsd\nasdf\nasd\n\n\nas\nasdf\n\n\n\n\nasdf\n\nsdf\nasdf\n\n\n\n\n\nasfdasdf\n\n\n\n\nsafdadfasdf";
    //private String s = rankBoard.toString();

    // End of variables declaration//GEN-END:variables
}
